env:
  browser: true
  es6: true
extends:
  - react-app
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - '@typescript-eslint'
rules:
  import/no-unresolved: off
  import/extension: off
  no-use-before-define: off
  indent: [2, 2]
overrides:
  - files:
      - '**/*.ts?(x)'
    rules:
      additional-typescript-only-rule: off
      import/extension: off
      react/jsx-filename-extension: [ 2, { 'extensions': [ '.js', '.jsx', '.ts', '.tsx' ] } ]
      indent: [2, 2]
